services:
  - type: web
    name: csm-app
    env: node
    plan: free
    buildCommand: npm ci
    startCommand: node server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8888
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
    autoDeploy: true
